### ISSUE TITLE
Does not run on Linux

### ISSUE THREAD

**Issue by rollinger** [BUTR/Bannerlord.BUTRLoader#97]
BUTRLoader does not start up on Linux (Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

Vanilla Launcher loads instead

**Comment by Aragas** [comment]
Sorry for the delayed answer! I guess that Proton was used? Was `net472` installed? Was the `.config` file present?
If the config was there and `net472` was not installed, could you try to install it? Because by default the game is using mono as the runtime, it might work with a proper net472 runtime

**Comment by TheDukeofErl** [comment]
> A similar Linux issue that has some info about installing `dotnet472`

This seems to be the fix here as well.
